### PR TITLE
Update 01-intro.Rmd

### PR DESCRIPTION
**Pull request by nazmulhasan202**
Typo correction needed

### CODE REVIEW

**Review by alexd106 — APPROVED** [review]
Good catch. Many thanks.

**Comment by alexd106** [comment]
Have acknowledged you in thanks.

**Comment by nazmulhasan202** [comment]
Thanks a lot. I really appreciate it!

Regards,
Nazmul Hasan
PhD Student and Graduate Assistant
Department of Systems and Industrial Engineering
University of Arizona

**Comment by nazmulhasan202** [comment]
You are most welcome!

Regards,
Nazmul Hasan
PhD Student and Graduate Assistant
Department of Systems and Industrial Engineering
University of Arizona

**Pull request merged**
