### PR TITLE
Update 04-base_r_graphics.Rmd

### PR DESCRIPTION
**Pull request by gungorMetehan**
5 typos and 1 'play around'

### CODE REVIEW

**Comment by alexd106** [comment]
Thanks again for spotting these. Before I merge this pull request can you change `type n` to `type = n`
i.e

`type = p`, `type = h`, `type = s`, and `type n` arguments in `plot()`

to 
`type = p`, `type = h`, `type = s`, and `type = n` arguments in `plot()`

**Comment by alexd106** [comment]
Also, `with()\index{with()}` should be 
`with()`\index{with()}

**Review by gungorMetehan — COMMENTED** [review]
It seems O.K

**Comment by gungorMetehan** [comment]
I changed it @alexd106
btw, I couldn't find 'with()\index{with()}'. It seems O.K.

**Comment by alexd106** [comment]
I have added these manually. Thanks

**Pull request closed without merging**
