### PR TITLE
Update 02-basics.Rmd

### PR DESCRIPTION
**Pull request by it1mutiti**

### CODE REVIEW

**Comment by alexd106** [comment]
Thanks. I will add you as an acknowledgement when I next build the book.

**Comment by alexd106** [comment]
Would you like me to include your github user name in the acknowledgements or your full name (if so I will need this info)?

**Comment by it1mutiti** [comment]
Dear Dr Alex

Yes please, you may include my name.

Full Name: Irvine Tatenda Mutiti
MSc. Applied Bioscience
Anglia Ruskin University (Cambridge)

Your book is very helpful. When I started learning R it seemed to be very
complicated, but it looks way easier now thanks to your well explained
book.

Kind regards,
Irvine

**Comment by it1mutiti** [comment]
Thank you

**Pull request merged**
